- name: create directory 
  become: true
  file: 
    path: /home/ubuntu/backend
    state: directory
    mode: 0755
- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes    
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present    
- name: copy artifact
  become: true
  copy: 
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu/backend/backend.tar.gz    
- name: Extract artifact files
  become: true
  shell: |
    cd /home/ubuntu/backend
    tar -xvf backend.tar.gz
- name: Executing node
  become: true
  environment:
    ENVIRONMENT: "production"
    TYPEORM_CONNECTION: "postgres"
    TYPEORM_MIGRATIONS_DIR: "./src/migrations"
    TYPEORM_MIGRATIONS: ./src/migrations/*.ts
    TYPEORM_ENTITIES: "./src/modules/domain/**/*.entity.ts"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"    
  shell: |
    cd /home/ubuntu/backend
    pm2 stop default
    pm2 start npm -- start
