- name: create directory 
  become: true
  file: 
    path: /home/ubuntu/backend
    state: directory
    mode: 0755
- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes    
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present    
- name: copy artifact
  become: true
  copy: 
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu/backend/backend.tar.gz    
- name: Extract artifact files
  become: true
  shell: |
    cd /home/ubuntu/backend
    tar -xvf backend.tar.gz
- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 stop default
    pm2 start npm -- start
